services:
  - type: web
    name: flyrank-triage-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: MODEL_PATH
        value: Flyrank_50trees.pkl
      - key: HF_REPO_ID
        value: simon-okosodo-ds/flyrank-triage-model
      - key: MODEL_URL
        value: https://github.com/simon-okosodo-ds/flyrank-triage-api/releases/download/v1.0.0/Flyrank.model.pkl
